apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: dhileep2
    provider: gitlab
    repository: quickstart
    gitops.jenkins-x.io/pipeline: 'namespaces'
  name: dhileep2-quickstart
  namespace: jx
spec:
  httpCloneURL: https://gitlab.com/dhileep2/quickstart.git
  org: dhileep2
  provider: https://gitlab.com
  providerKind: gitlab
  providerName: github
  repo: quickstart
  scheduler:
    kind: ""
    name: in-repo
  url: https://gitlab.com/dhileep2/quickstart
